config/routes.rb
EventManager::Application.routes.draw do
  match '/admin' => "admin#index"
  match '/admin/mark_paid' => "admin#mark_paid"
  
  root :to => 'payments#index'
  
  match '/book' => 'payments#new', :as => :new_ticket
  get 'payments/thankyou'
  post 'payments/thankyou'
  post 'payments/cancel'
  get 'payments/ipn'
  post 'payments/ipn'
  
  resources :payments do
    post 'create'
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessible :email, :table_code
  
  has_many :tickets, :dependent => :destroy
  
  validates :email, :presence => true,
                    :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
  validates :price, :presence => true
  validates :table_code, :length => {:maximum => 16}
  
  before_validation :set_price
  
  def fully_paid?
    self.paid == self.price
  end
  
  # returns if this table is discounted for bulk purchase
  def discounted?
    tickets.size == 8
  end
  
  def set_table_code
    # Set the table_code if not given
    if self.table_code.nil? || self.table_code.blank?
      self.table_code = "TABLE#{id}"
    end
  end
  
  private
  def set_price
    if self.new_record?
      # Only set this once, if it is unset
      self.price = tickets.inject(0) do |sum, ticket|
        sum += ticket.price.price
      end
      
      # Apply 8 seat discount
      # TODO: validate tickets size is in 1..8
      if self.discounted?
        self.price -= 4800
      end
    end
  end
  
end

app/models/price.rb
class Price < ActiveRecord::Base
  attr_accessible :price, :name
  
  has_many :tickets
  
  validates :price, :presence => true
  validates :name, :presence => true
end

app/models/table.rb
class Table
  attr_reader :id, :tickets
  
  def initialize(id, tickets)
    @id = id
    @tickets = tickets
  end
  
  # Class methods
  def self.all
    Ticket.all.select { |t|
      t.payment.fully_paid?
    }.group_by { |t|
      t.payment.table_code
    }.map { |id, t|
      Table.new(id, t)
    }
  end
  
  def self.find(id)
    self.all.select {|x| x.id == id}.first
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :dietary_req, :name, :price_id, :student_id, :faculty
  
  belongs_to :payment
  belongs_to :price
  
  validates :name, :presence => true
  validates :price_id, :presence => true
  validates :dietary_req, :length => {:maximum => 512}, :presence => {:message => "must be supplied"}
  validates :student_id, :presence => true
  validates :faculty, :presence => true
  validates :payment_id, :presence => true, :unless => Proc.new { |t| t.new_record? }
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :require_admin
  
  def index
    @payments = Payment.all.reverse
    @tables = Table.all
  end

  def mark_paid
    @payment = Payment.find(params[:payment_id])
    

    if @payment
    #   @payment.paid = @payment.price
    #   @payment.save
    #   TicketMailer.ticket_purchase_notification(@payment).deliver
      @payment.paid = @payment.price
      @payment.save!
      TicketMailer.ticket_purchase_notification(@payment).deliver
      redirect_to admin_path, :notice => "Payment #{@payment.id} has been paid."
    else
      redirect_to admin_path, :notice => "Couldn't find that payment :("
    end
  end
  
  private
  def require_admin
    authenticate_or_request_with_http_basic do |username, password|
      username == "admin" && password == ENV["ADMIN_PASS"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_filter :requires_transaction, :only => [:show]
  
  def index
    
  end
  
  def new
    @payment = Payment.new
    if params[:seats]
      if params[:seats].to_i > 8
        params[:seats] = 8
      end
      @payment.tickets = params[:seats].to_i.times.to_a.map {Ticket.new}
    else
      @payment.tickets = [Ticket.new]
    end
  end
  
  # This creates a payment for you
  def create
    payment = Payment.new(params[:payment])
    
    params[:tickets].each do |key, ticket|
      payment.tickets.build(ticket)
    end
    
    if payment.save
      payment.set_table_code
      payment.save
      
      session[:transaction] = payment.id
      redirect_to payment
    else
      @payment = payment
      render :new
    end
    # TODO: table params[:ticket][:table_id]
  end
  
  # This is where you can choose a payment option
  # FILTER: transaction
  def show
    @payment = Payment.find(params[:id])     
  end
  
  
  def thankyou
    # raise params.inspect
    # @payment = Payments.find(params[:item_number])
    # if @payment
    #   @payment.paid = @payment.price
    #   @payment.save
    #   TicketMailer.ticket_purchase_notification(@payment).deliver
    # else

    # end
  end

  def ipn
    # Get the request
    # Replay it to paypal
    # Get the result of that request
    query_string = request.env["QUERY_STRING"]
    #response = Faraday.post(env["PAYPAL_BUYNOW_SITE"] + "?" + query_string)

    conn = Faraday.new(:url => env["PAYPAL_BUYNOW_SITE"]) do |faraday|
     faraday.request  :url_encoded             # form-encode POST params
     faraday.response :logger                  # log requests to STDOUT
     faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
    end

    conn.post do |req|
     req.url '/'
     req.headers['Content-Type'] = request.env["HTTP_ACCEPT"]
     req.body = query_string
    end

    raise conn.inspect
  end
  
  # cancel transaction
  def cancel
    # unable to do this :( GATEWAY.void doesn't work like that
    #   so we set it up with our session logic so it's not
    #   possible without our private keys
    session[:transaction] = nil
    redirect_to root_path, :notice => "Payment Cancelled"
  end
  
  private
  def requires_transaction
    if params[:id].to_i != session[:transaction]
      @message = "Invalid session id"
      render :action => 'error'
      return
    end
  end
  
  def check_token
    redirect_to :action => 'index' unless params[:token]
    @payment = Payment.where(:token => params[:token]).first
    
    # Check session
    if @payment.id != session[:transaction]
      @message = "Invalid PayPal token"
      render :action => 'error'
      return
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def price_name(x)
    "#{x.name} (#{number_to_currency(x.price / 100)})"
  end
  
  def filter_errors(x)
    x.full_messages.uniq.reject{|x| x == 'Tickets is invalid'}
  end
end

app/views/admin/index.html.erb
<div class="page-header">
  <h1>Admin</h1>
</div>

<h2>Payments</h2>

<p>This is all the payments, regardless of paid or not.</p>

<table class="table table-striped" style="font-size: 1.3em">
  <thead>
    <tr>
      <th>Order Num </th>
      <th>Email</th>
      <th>Tickets</th>
      <th>Should have paid</th>
      <th>Bulk Discount?</th>
      <th>Table Code</th>
      <th>Created</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.id %></td>
        <td><strong><%= payment.email %></strong></td>
        <td>
          <% payment.tickets.group_by(&:price).each do |price, tickets| %>
            [<%= price.name %>: <%= tickets.size %>]
          <% end %>
        </td>
        <td><em><%= number_to_currency(payment.price / 100) %></em></td>
        <td><%= payment.discounted? %></td>
        <td><%= payment.table_code %></td>
        <td><%= payment.created_at.to_formatted_s(:short) %></td>
        <td>
          <%= link_to_unless payment.paid?, "Has Paid", admin_mark_paid_path(:payment_id=>payment.id), :method => :post do %>
            Paid
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Tables</h2>

<table class="table table-striped" style="font-size: 1.3em">
  <thead>
    <tr>
      <th>Table Code</th>
      <th>Name</th>
      <th>Dietary Requirements</th>
      <th>Ticket Type</th>
      <th>Payee</th>
      <th>Time</th>
    </tr>
  </thead>
  <tbody>
    <% @tables.each do |table| %>
      <% table.tickets.each do |ticket| %>
        <tr>
          <% if table.id %>
            <td><strong><%= table.id %></strong></td>
          <% else %>
            <td><em>None</em></td>
          <% end %>
          <td><strong><%= ticket.name %></strong></td>
          <td><%= ticket.dietary_req %></td>
          <td><%= ticket.price.name %></td>
          <td><%= ticket.payment.email %></td>
          <td><%= ticket.created_at.to_formatted_s(:short) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Event Manager" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="container">
      <div class="content">
        <div class="row">
          <div class="span12 top-banner-container">
            <img src="/assets/spring-ball-FB-banner.png"/>
          </div>
        </div>
        <div class="row">
           <div class="span12">
              <%= yield %>
            </div>
        </div>
      </div>

      <footer>
        <hr>
        <p>If you have trouble buying tickets or have any questions, please email us at pgc.events [at] arc.unsw.edu.au </p>
        
      </footer>

    </div>
    
    <%= javascript_include_tag "application" %>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-34545224-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
  </body>
</html>

app/views/payments/_form.html.erb
<% if @payment.errors.any? %>
  <div class="alert alert-error alert-block">
    <h4 class="alert-heading">Could not book tickets because:</h4>
    <p>
      <ul>
        <% @payment.tickets.each do |ticket| %>
          <% ticket.errors.full_messages.each do |e| %>
            <li><%= e %></li>
          <% end %>
        <% end %>

        <% @payment.errors.full_messages.each do |m| %>
          <li><%= m %></li>
        <% end %>
      </ul>
    </p>
  </div>
<% end %>

<%= form_for @payment, :html => { :class => 'form-horizontal' } do |f| %>
  <p>Items with a * are required, but for dietary requirements, student ID, and faculty, you can set the value to 'none' or 'n/a'.</p>
  <% @payment.tickets.each_with_index do |ticket, i| %>
    <% i += 1 %>
    <div id="ticket_<%= i %>">
      <hr>
      <h3>Ticket <%= i %></h3>
      <%= fields_for "tickets[#{i}]", ticket do |f| %>
        <%= render :template => 'payments/_tickets', :locals => {:f => f} %>
      <% end %>
    </div>
  <% end %>
  
  <script type="text/javascript">
    window.ticket_count = <%= @payment.tickets.size %>;
  </script>
  
  <script id="ticket_template" type="text/template">
    <div id="ticket_{{count}}">
      <hr>
      <h3>Ticket {{ count }}:</h3>
      <%= fields_for "tickets[{{count}}]" do |f| %>
        <%= render :template => 'payments/_tickets', :locals => {:f => f} %>
      <% end %>
    </div>
  </script>
  
  <div id="ticket_bottom"></div>
  
  <p>
    <%= link_to_function '<i class="icon-plus"></i> Add Additional Ticket'.html_safe, "add_ticket()", :class => 'btn btn-success', :id => 'ticket_more' %>
    <%= link_to_function '<i class="icon-trash"></i> Remove Last Ticket'.html_safe, "remove_ticket()", :class => 'btn btn-danger', :id => 'ticket_delete' %>
  </p>
  
  <p id="discount" class="alert alert-success" style="font-size: 1.2em">
    Booking 8 tickets together gives a <span style="color: red"><strong>$48</strong></span> discount.
  </p>
  
  <hr>
  <h3>General Information For This Booking</h3>
  <p>Please enter an email address below to use with this booking. We will use this to identify this booking and contact you if we need to. We'll delete it after the event. We don't like spam either.</p>
  <p>Also, if you are attending with friends who already have their tickets, ask them for their table code and enter it below to let us know that you'd like to be seated with them. We will try to accomodate these requests as best we can (within the limits of finite table sizes).</p>
  <div class="control-group">
    <%= f.label 'Email', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="control-group">

    <%= f.label 'Table Name (optional).', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :table_code, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    
    <%= f.submit 'Book Tickets', :class => 'btn btn-primary' %>
    
    <%= link_to 'Cancel', root_path, :class => 'btn' %>
  </div>
<% end %>

app/views/payments/_tickets.html.erb
<div class="control-group">
  <%= f.label 'Name *', :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :name, :class => 'text_field' %>
  </div>
</div>
<div class="control-group">
  <%= f.label 'Dietary Requirements *', :class => 'control-label' %>
  <div class="controls">
    <%= f.text_area :dietary_req, :class => 'text_area', :rows => 2 %>
  </div>
</div>
<div class="control-group">
  <%= f.label "Student ID *", :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :student_id, :class => 'text_field'%>
  </div>
</div>
<div class="control-group">
  <%= f.label "Faculty *", :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :faculty, :class => 'text_field' %>
  </div>
</div>
<div class="control-group">
  <%= f.label 'Ticket Type', :class => 'control-label' %>
  <div class="controls">
    <%= f.select :price_id, Price.all.map {|x| [price_name(x), x.id]} %>
  </div>
</div>

app/views/payments/complete.html.erb
<div class="page-header">
  <h1>Payment Complete</h1>
</div>

<p>Your payment of <strong><%= number_to_currency(@payment.price / 100) %></strong> is complete.</p>

<p>We've emailed your provided address with more details and a confirmation of purchase. You can now close this window and get back to your important Postgrad work.</p>

<p>Thanks and see you at the ball!</p>

app/views/payments/confirm.html.erb
<div class="page-header">
  <h1>Payment</h1>
</div>

<p>Total Price: <strong><%= number_to_currency(@payment.price / 100) %></strong></p>

<p>Are you sure you want to make this payment?</p>

<%= form_tag({:action => 'complete', :token => params[:token], :payer_id => params[:PayerID]}, {:id => 'send_payment_form'}) do %>
  <%= submit_tag 'Complete Payment', :id => "send_payment", :class => 'btn btn-primary' %>
<% end %>

<p id="send_progress" style="display: none">Please wait...</p>

<%= form_tag :action => 'cancel' do %>
  <%= submit_tag 'Cancel Payment', :class => 'btn btn-danger' %>
<% end %>

app/views/payments/error.html.erb
<div class="page-header">
  <h1>Payment Error</h1>
</div>

<p><%= link_to "Return Home", root_path %></p>
<hr>

<div style="font-size: 1.3em">
  <p>Unfortunately an error occurred: <%= @message %></p>
  <p>Please contact support to resolve this issue.</p>
</div>

app/views/payments/index.html.erb
<div class="hero-unit">
  <div class="span10">
    <p>The Arc Postgraduate Council invites you to the inaugural PGC Spring Ball. Come along to the Roundhouse on Friday October 5th for a fantastic night with your friends and colleagues. This ball is the first of its kind and organised  by Arc and your Postgraduate Council. Tickets are $66 for Arc Members and $76 for non-Arc Members. Booking a table of eight is even cheaper ($60/$70). Tickets  include a two-course meal with canapes, drinks and entertainment by jazz artists and DJ 'Potential Ember'.</p>
    <p>
      To buy your tickets, simply select tickets / table below, enter your details, pay securely via Credit Card or Paypal, and we'll send you your tickets electronically!
    </p>
    <p>
      <%= link_to "Book now", new_ticket_path, :class => "btn btn-primary btn-large" %>
      <%= link_to "Book a table (8 seats)", new_ticket_path(:seats => 8), :class => "btn btn-primary btn-large" %>
    </p>
  </div>
</div>
<div class="row image-row span12">
  <div class="span4">
    <img src="/assets/group1_cropped.jpg"/>
    <p>2 course meal and canapes</p>
  </div>
  <div class="span4">
    <img src="/assets/group2_cropped.jpg"/>
    <p>Great Music from a Jazz band and DJ Potential Ember</p>
 </div>
  <div class="span4">
    <img src="/assets/group3_cropped.jpg"/>
    <p>Fellow Postgrads from around campus!</p>
  </div>
</div>

app/views/payments/new.html.erb
<div class="page-header" style="border-bottom: none">
  <h1>Book Tickets</h1>
</div>

<p class="well" style="font-size: 1.3em">
  Booking 8 tickets (a full table) together gives a
  <span style="color: red"><strong>$48</strong></span> discount.
</p>

<%= render :partial => 'form' %>

app/views/payments/show.html.erb
<div class="page-header">
  <h1>Payment</h1>
</div>

<table class="table table-striped" style="font-size: 1.3em">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @payment.tickets.each do |ticket| %>
      <tr>
        <td><strong><%= ticket.name %></strong></td>
        <td><%= ticket.price.name %></td>
        <td><em><%= number_to_currency(ticket.price.price / 100) %></em></td>
      </tr>
    <% end %>
    
    <% if @payment.discounted? %>
      <tr>
        <td colspan="2">
          Discount
        </td>
        <td>
          <strong>-<%= number_to_currency(4800 / 100) %></strong>
        </td>
      </tr>
    <% end %>
    
    <tr>
      <td colspan="2">
        Total Price
      </td>
      <td>
        <strong><%= number_to_currency(@payment.price / 100) %></strong>
      </td>
    </tr>
  </tbody>
</table>

<p>
  <form name="_xclick" action="<%= ENV["PAYPAL_BUYNOW_SITE"] %>" method="post">
    <input type="hidden" name="cmd" value="_xclick">
    <input type="hidden" name="business" value="<%= ENV["PAYPAL_EMAIL"] %>">
    <input type="hidden" name="lc" value="AU">
    <input type="hidden" name="currency_code" value="AUD">
    <input type="hidden" name="item_name" value="PGC Ball Tickets (order number <%= @payment.id %>)">
    <input type="hidden" name="item_number" value="<%= @payment.id %>">
    <input type="hidden" name="amount" value="<%= @payment.price/100 %>">
    <input type="hidden" name="button_subtype" value="services">
    <input type="hidden" name="return" value="<%= payments_thankyou_url %>">
    <input type="hidden" name="bn" value="PP-BuyNowBF:btn_paynowCC_LG.gif:NonHostedGuest">
    <input type="image" src="https://www.paypalobjects.com/en_AU/i/btn/btn_paynowCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online." class="paypal-buynow-button">
    <img alt="" border="0" src="https://www.paypalobjects.com/en_AU/i/scr/pixel.gif" width="1" height="1">

  </form>
  <p>
    You will be redirected to the Paypal site to pay. After the payment clears, we will send you an email with your tickets. If you don't hear from us in 3-5 business days, please contact pgc.info@arc.unsw.edu.au so we can check your payment details and send you your tickets.
  </p>

</p>

<hr>

app/views/payments/thankyou.html.erb
<div class="page-header">
  <h1>Payment Processing</h1>
</div>

<p>Your transaction is being processed.</p>

<p>Once we receive the money from Paypal, we'll send you an email with tickets. If you don't hear from us in 3-5 business days, please contact pgc.info@arc.unsw.edu.au so we can check your payment details and send you your tickets. </p>
<p>You can now close this window and get back to your important Postgrad work :)</p>

<p>Thanks and see you at the ball!</p>

app/views/tickets/new.html.erb
<%- model_class = Ticket -%>
<div class="page-header">
  <h1>Book Ticket</h1>
</div>
<%= render :partial => 'form' %>